### ISSUE TITLE
Why is this published on GitHub?

### ISSUE THREAD

**Issue by gardner** [lumiere-video/lumiere-video.github.io#1]
Is there an intention to open source the model weights or code?

**Comment by MrWu-at-msv** [comment]
The paper is publicly available at arxiv.
Easy to replicate.

**Comment by gardner** [comment]
I am going to share feedback based on a trend I am seeing. It's not just this repository, so, please take it with a grain of salt:

It is misleading to host the demo video webpage on GitHub. People assume there is code or associated weights published because GitHub is a place for people to collaborate. There seems to be a trend with research papers hosting non-code on GitHub and then adding the link in their paper.

I know that it was not your intention but I find it frustrating and deceptive.

Thanks for reading my feedback.

**Comment by 2blackbar** [comment]
gardner there are smart people who can implement this after reading the paper so chill, its a thing yes but at least they released paper with explanations.
Dreambooth was never released officially by googles and yet people figured it out from the paper.
